services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:4000"
    restart: always
