version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
      timeout: 5s

  backend:
    build: ./backend  # Make sure this matches your backend folder
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend  # Make sure this matches your frontend folder
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:4000"
    restart: always

volumes:
  redis_data:
    driver: local
